ALTER TYPE "ConnectionStatus" RENAME VALUE 'MEET_NOW' TO 'CHILL';
ALTER TYPE "ConnectionStatus" RENAME VALUE 'FWB' TO 'PARTY';
ALTER TYPE "ConnectionStatus" RENAME VALUE 'JUST_FRIENDS' TO 'FOODIE';
ALTER TYPE "ConnectionStatus" RENAME VALUE 'DATING' TO 'OPEN_TO_ANYTHING';
