ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'SERIOUS_RELATIONSHIP';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'CASUAL_DATING';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'FRIENDS_FIRST';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'OPEN_TO_ANYTHING';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'EVENT_BUDDY';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'CHAT_FIRST';
ALTER TYPE "ConnectionStatus" ADD VALUE IF NOT EXISTS 'SEX';
